import { useState } from "react";
import { getRecommendations } from "../utils/recommendationAlgorithm";
import { Preference, FoodRecommendation } from "../types";

const INITIAL_PREFERENCES: Preference = {
  cuisine: "",
  flavor1: "",
  flavor2: "",
  foodType1: "",
  foodType2: "",
  vibe: "",
};

const cuisines = [
  "Peranakan",
  "Indian",
  "Malay",
  "Western",
  "Chinese",
  "Thai",
  "Indonesian",
];
const flavors = ["Sweet", "Spicy", "Sour", "Umami", "Salty"];
const foodTypes = [
  "Non-Veg",
  "Non-Halal",
  "Seafood",
  "Meat",
  "Vegetarian",
  "Halal",
];
const vibeTypes = ["Casual", "Fancy", "Street Food & Snacks", "Comfort Food"];

const selectStyles = {
  width: "100%",
  padding: "12px",
  fontSize: "16px",
  backgroundColor: "#dc4f9c",
  color: "white",
  border: "none",
  borderRadius: "4px",
  cursor: "pointer",
  appearance: "none" as const,
  WebkitAppearance: "none" as const,
};

export function PreferenceForm() {
  const [preferences, setPreferences] =
    useState<Preference>(INITIAL_PREFERENCES);
  const [recommendations, setRecommendations] = useState<FoodRecommendation[]>(
    [],
  );

  const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const { name, value } = e.target;
    setPreferences((prev) => ({
      ...prev,
      [name]: value,
    }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const recs = getRecommendations(preferences);
    setRecommendations(recs);
  };

  const handlePrint = () => {
    const printWindow = window.open("", "_blank");
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Makan Match - Your Food Recommendations</title>
            <style>
              body {
                font-family: Arial, sans-serif;
                padding: 20px;
                max-width: 600px;
                margin: 0 auto;
              }
              h1 {
                color: #442F91;
                margin-bottom: 20px;
              }
              .preferences {
                margin-bottom: 30px;
                padding: 15px;
                background-color: #f8fbf8;
                border-radius: 4px;
              }
              .dish {
                margin-bottom: 15px;
                padding: 10px;
                border-bottom: 1px solid #eee;
              }
              .score {
                color: #dc4f9c;
                font-weight: bold;
              }
              @media print {
                body {
                  padding: 0;
                }
                .preferences {
                  background-color: #f8f8f8;
                }
              }
            </style>
          </head>
          <body>
            <h1>Makan Match Recommendations</h1>
            <div class="preferences">
              <strong>Your Preferences:</strong><br>
              ${preferences.cuisine ? `Cuisine: ${preferences.cuisine}<br>` : ""}
              ${preferences.flavor1 ? `Flavor 1: ${preferences.flavor1}<br>` : ""}
              ${preferences.flavor2 ? `Flavor 2: ${preferences.flavor2}<br>` : ""}
              ${preferences.foodType1 ? `Food Type 1: ${preferences.foodType1}<br>` : ""}
              ${preferences.foodType2 ? `Food Type 2: ${preferences.foodType2}<br>` : ""}
              ${preferences.vibe ? `Vibe: ${preferences.vibe}<br>` : ""}
            </div>
            <h2>Top Recommended Dishes</h2>
            ${recommendations
              .map(
                (dish, index) => `
              <div class="dish">
                ${index + 1}. ${dish.name} - <span class="score">Match Score: ${dish.score}%</span>
              </div>
            `,
              )
              .join("")}
            <p style="margin-top: 30px; font-size: 12px; color: #666;">
              Generated by Makan Match on ${new Date().toLocaleDateString()}
            </p>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div
      style={{
        width: "100%",
        maxWidth: "800px",
        margin: "0 auto",
        padding: "20px",
        display: "flex",
        flexDirection: "column",
        gap: "20px",
      }}
    >
      <form
        onSubmit={handleSubmit}
        style={{ display: "flex", flexDirection: "column", gap: "20px" }}
      >
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
            gap: "20px",
          }}
        >
          {/* Cuisine Select */}
          <div>
            <label
              style={{ display: "block", marginBottom: "8px", color: "#333" }}
            >
              Cuisine
            </label>
            <select
              name="cuisine"
              value={preferences.cuisine}
              onChange={handleChange}
              style={selectStyles}
            >
              <option value="">Select Cuisine</option>
              {cuisines.map((cuisine) => (
                <option key={cuisine} value={cuisine}>
                  {cuisine}
                </option>
              ))}
            </select>
          </div>

          {/* Flavor 1 Select */}
          <div>
            <label
              style={{ display: "block", marginBottom: "8px", color: "#333" }}
            >
              Flavor 1
            </label>
            <select
              name="flavor1"
              value={preferences.flavor1}
              onChange={handleChange}
              style={selectStyles}
            >
              <option value="">Select Flavor</option>
              {flavors.map((flavor) => (
                <option key={flavor} value={flavor}>
                  {flavor}
                </option>
              ))}
            </select>
          </div>

          {/* Flavor 2 Select */}
          <div>
            <label
              style={{ display: "block", marginBottom: "8px", color: "#333" }}
            >
              Flavor 2
            </label>
            <select
              name="flavor2"
              value={preferences.flavor2}
              onChange={handleChange}
              style={selectStyles}
            >
              <option value="">Select Flavor</option>
              {flavors.map((flavor) => (
                <option key={flavor} value={flavor}>
                  {flavor}
                </option>
              ))}
            </select>
          </div>

          {/* Food Type 1 Select */}
          <div>
            <label
              style={{ display: "block", marginBottom: "8px", color: "#333" }}
            >
              Food Type 1
            </label>
            <select
              name="foodType1"
              value={preferences.foodType1}
              onChange={handleChange}
              style={selectStyles}
            >
              <option value="">Select Food Type</option>
              {foodTypes.map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
          </div>

          {/* Food Type 2 Select */}
          <div>
            <label
              style={{ display: "block", marginBottom: "8px", color: "#333" }}
            >
              Food Type 2
            </label>
            <select
              name="foodType2"
              value={preferences.foodType2}
              onChange={handleChange}
              style={selectStyles}
            >
              <option value="">Select Food Type</option>
              {foodTypes.map((type) => (
                <option key={type} value={type}>
                  {type}
                </option>
              ))}
            </select>
          </div>

          {/* Vibe Select */}
          <div>
            <label
              style={{ display: "block", marginBottom: "8px", color: "#333" }}
            >
              Vibe
            </label>
            <select
              name="vibe"
              value={preferences.vibe}
              onChange={handleChange}
              style={selectStyles}
            >
              <option value="">Select Vibe</option>
              {vibeTypes.map((v) => (
                <option key={v} value={v}>
                  {v}
                </option>
              ))}
            </select>
          </div>
        </div>

        <button
          type="submit"
          style={{
            width: "100%",
            padding: "15px",
            fontSize: "16px",
            backgroundColor: "#442F91",
            color: "white",
            border: "none",
            borderRadius: "4px",
            cursor: "pointer",
            marginTop: "20px",
          }}
        >
          Get Recommendations
        </button>
      </form>

      {recommendations.length > 0 && (
        <div style={{ marginTop: "30px" }}>
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
            }}
          >
            <h2 style={{ color: "#333" }}>Recommended Dishes</h2>
            <button
              onClick={handlePrint}
              style={{
                padding: "10px 20px",
                fontSize: "14px",
                backgroundColor: "#dc4f9c",
                color: "white",
                border: "none",
                borderRadius: "4px",
                cursor: "pointer",
              }}
            >
              Print Recommendations
            </button>
          </div>
          <ul style={{ listStyle: "none", padding: 0, marginTop: "20px" }}>
            {recommendations.map((dish, index) => (
              <li
                key={index}
                style={{
                  padding: "15px",
                  marginBottom: "10px",
                  backgroundColor: "#fff",
                  borderRadius: "4px",
                  boxShadow: "0 2px 4px rgba(0,0,0,0.1)",
                }}
              >
                {dish.name} - Match Score: {dish.score}%
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}
